:- include('personagens.pl').

homem(anakin).
homem(obi_wan).
homem(luke).
homem(yoda).
homem(palpatine).
homem(han_solo).
homem(ben_solo).
homem(chewbacca).
homem(dookan).
homem(darth_tyranus).
homem(darth_andeddu).
homem(darth_krayt).
homem(darth_andeddu).
homem(darth_badon).
homem(darth_bane).
homem(darth_caedus).
homem(darth_krayt).
homem(darth_krayt).
homem(darth_nihilus).
homem(darth_revan).
homem(kylo_ren).
homem(lando).
homem(windu).
homem(qui_gon).
homem(ben).
homem(kylo).
homem(darth_sidious).
homem(finn).
homem(tarkin).
homem(darth_maul).
homem(poe).
homem(finis).
homem(cliegg).
homem(hux).
homem(finis).
homem(piett).
homem(ruweee).
homem(cliegg).
homem(plo_koon).
homem(din).
homem(boba).
homem(jango).
homem(krrsantan).
homem(bane).
homem(paz_vizla).
homem(fortuna).
homem(paratus).
