:- include('personagens.pl').
mulher(aayla).
mulher(ahsoka).
mulher(bo_katan).
mulher(cara_dune).
mulher(fennec).
mulher(jobal).
mulher(jyn).
mulher(kanata).
mulher(leia).
mulher(luminara).
mulher(mara_jade).
mulher(padme).
mulher(phasma).
mulher(rey).
mulher(sabine).
mulher(satine).
mulher(shaak_ti).
mulher(shmi).
